apiVersion: v1
kind: Service
metadata:
  name: supervisor-svc
  namespace: aegis-mesh
spec:
  selector:
    app: aegis-supervisor
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
