apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-workloads
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/GosYao/AegisShield.git
    targetRevision: main
    path: gitops/ai-workloads
  destination:
    server: https://kubernetes.default.svc
    namespace: aegis-mesh
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: hf-secret
      jsonPointers:
        - /data
        - /stringData
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false   # Namespace created in step 4 before ArgoCD syncs this
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
