apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/kserve/charts
      chart: kserve-crd
      targetRevision: v0.13.0
    - repoURL: oci://ghcr.io/kserve/charts
      chart: kserve
      targetRevision: v0.13.0
      helm:
        values: |
          kserve:
            controller:
              image: kserve/kserve-controller
            modelmesh:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
