apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-ksa
  namespace: aegis-mesh
  annotations:
    # Workload Identity: binds this KSA to the GCP SA that has GCS read access.
    iam.gke.io/gcp-service-account: aegis-agent-sa@gyao-bde-demo.iam.gserviceaccount.com
