apiVersion: v1
kind: Service
metadata:
  name: agent-svc
  namespace: aegis-mesh
spec:
  selector:
    app: aegis-agent
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
